name: abllseducation
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get: any
  http: any
  flutter_svg: any
  url_launcher: any
  pod_player: ^0.1.0

  firebase_core: any
  firebase_auth: any
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0

  image_picker: any
  shared_preferences: any
  percent_indicator: ^4.2.3
  path_provider: ^2.0.12
  google_fonts:
  native_pdf_renderer: ^5.0.0+1
  pdf: ^3.9.0
  intl:
  open_file: ^3.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/
  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf
        - weight: 400
        - asset: fonts/Arial_Bold.ttf
          weight: 700
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
